[project]
name = "keenetic-vpn-switcher"
version = "0.1.0"
description = "Toggle VPN for specified device MAC address on Keenetic router"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["requests>=2.32.5", "python-telegram-bot>=22.5"]
